version: '3'

services: 
    ecoleta-api:
        image: ts-ecoleta
        container_name: ecoleta-api
        build: .
        command: npm run dev
        ports:
            - "3000:3000"
        volumes: 
            - dev:/usr/app   

volumes:
    dev: